sudo: required
services:
  - docker

before_install:
  - docker build  -t dockertuka/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dockertuka/react-test npm test -- --coverage

after_success:
  - docker build -t dockertuka/multi-client ./client
  - docker build -t dockertuka/multi-nginx ./nginx
  - docker build -t dockertuka/multi-server ./server
  - docker build -t dockertuka/multi-worker ./worker

# Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Push them to dockerhub
  - docker push dockertuka/multi-client
  - docker push dockertuka/multi-nginx
  - docker push dockertuka/multi-server
  - docker push dockertuka/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: "eu-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-181973116410"
  bucker_path: "multi-docker"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


  