sudo: required
services:
  - docker

before_install:
  - docker build  -t dockertuka/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dockertuka/react-test npm test -- --coverage

after_success:
  - docker build -t dockertuka/multi-client ./client
  - docker build -t dockertuka/multi-nginx ./nginx
  - docker build -t dockertuka/multi-server ./server
  - docker build -t dockertuka/multi-worker ./worker

# Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Push them to dockerhub
  - docker push dockertuka/multi-client
  - docker push dockertuka/multi-nginx
  - docker push dockertuka/multi-server
  - docker push dockertuka/multi-worker


  